### ISSUE TITLE
Trouble compiling todos example on Ubuntu 18.04 with default Qt 5.9.5

### ISSUE THREAD

**Issue by Pfeil** [woboq/qmetaobject-rs#15]
Hi, this is probably just an example of confusion about the debian/ubuntu qt packages, I'm really sorry for that. Using the same repo you use in the travis.yml, I can compile it (tried with qt5.11). On a relatively plain Ubuntu (default Qt packages etc) with Qt 5.9.5 (according to qmake --version) I get errors. Unfortunately I have no idea how to handle them. I am probably missing some qt packages or have wrong ones installed, but I can't tell which. Maybe you can tell me what to do, using the verbose output?

<details> 
  <summary>Verbose output</summary>

```
  $~/Git/qmetaobject-rs/examples/todos$ RUST_BACKTRACE=1 cargo build
   Compiling qmetaobject v0.0.1 (file:///home/verpfeilt/Git/qmetaobject-rs/qmetaobject)     
error: failed to run custom build command for `qmetaobject v0.0.1 (file:///home/verpfeilt/Git/qmetaobject-rs/qmetaobject)`
process didn't exit successfully: `/home/verpfeilt/Git/qmetaobject-rs/examples/todos/target/debug/build/qmetaobject-904b600a66b41e86/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
DEBUG = Some("true")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = None
running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/verpfeilt/Git/qmetaobject-rs/qmetaobject" "-I" "/usr/include/x86_64-linux-gnu/qt5" "-Wall" "-Wextra" "-std=c++11" "-o" "/home/verpfeilt/Git/qmetaobject-rs/examples/todos/target/debug/build/qmetaobject-6f9106977441dc85/out/rust_cpp/cpp_closures.o" "-c" "/home/verpfeilt/Git/qmetaobject-rs/examples/todos/target/debug/build/qmetaobject-6f9106977441dc85/out/rust_cpp/cpp_closures.cpp"
cargo:warning=src/lib.rs: In function ‘void __cpp_closure_4690954296995772382(FnBoxWrapper&, const QPointer<QThread>&)’:
cargo:warning=src/lib.rs:561:94: error: no matching function for call to ‘QMetaObject::invokeMethod(QObject*&, std::remove_reference<FnBoxWrapper&>::type, Qt::ConnectionType)’
cargo:warning=                 QMetaObject::invokeMethod(reciever, std::move(func_raw), Qt::QueuedConnection); // does not allow move-only
cargo:warning=                                                                                              ^
cargo:warning=In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:46:0,
cargo:warning=                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
cargo:warning=                 from /home/verpfeilt/Git/qmetaobject-rs/qmetaobject/qmetaobject_rust.hpp:20,
cargo:warning=                 from src/lib.rs:51:
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:406:17: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
cargo:warning=     static bool invokeMethod(QObject *obj, const char *member,
cargo:warning=                 ^~~~~~~~~~~~
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:406:17: note:   candidate expects 14 arguments, 3 provided
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:420:24: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
cargo:warning=     static inline bool invokeMethod(QObject *obj, const char *member,
cargo:warning=                        ^~~~~~~~~~~~
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:420:24: note:   no known conversion for argument 2 from ‘std::remove_reference<FnBoxWrapper&>::type {aka FnBoxWrapper}’ to ‘const char*’
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:437:24: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
cargo:warning=     static inline bool invokeMethod(QObject *obj, const char *member,
cargo:warning=                        ^~~~~~~~~~~~
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:437:24: note:   no known conversion for argument 2 from ‘std::remove_reference<FnBoxWrapper&>::type {aka FnBoxWrapper}’ to ‘const char*’
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:454:24: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
cargo:warning=     static inline bool invokeMethod(QObject *obj, const char *member,
cargo:warning=                        ^~~~~~~~~~~~
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:454:24: note:   no known conversion for argument 2 from ‘std::remove_reference<FnBoxWrapper&>::type {aka FnBoxWrapper}’ to ‘const char*’
cargo:warning=src/lib.rs:564:90: error: no matching function for call to ‘QMetaObject::invokeMethod(QGuiApplication*, std::remove_reference<FnBoxWrapper&>::type, Qt::ConnectionType)’
cargo:warning=                 QMetaObject::invokeMethod(qApp, std::move(func_raw), Qt::QueuedConnection);
cargo:warning=                                                                                          ^
cargo:warning=In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qobject.h:46:0,
cargo:warning=                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QObject:1,
cargo:warning=                 from /home/verpfeilt/Git/qmetaobject-rs/qmetaobject/qmetaobject_rust.hpp:20,
cargo:warning=                 from src/lib.rs:51:
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:406:17: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
cargo:warning=     static bool invokeMethod(QObject *obj, const char *member,
cargo:warning=                 ^~~~~~~~~~~~
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:406:17: note:   candidate expects 14 arguments, 3 provided
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:420:24: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
cargo:warning=     static inline bool invokeMethod(QObject *obj, const char *member,
cargo:warning=                        ^~~~~~~~~~~~
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:420:24: note:   no known conversion for argument 2 from ‘std::remove_reference<FnBoxWrapper&>::type {aka FnBoxWrapper}’ to ‘const char*’
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:437:24: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, Qt::ConnectionType, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
cargo:warning=     static inline bool invokeMethod(QObject *obj, const char *member,
cargo:warning=                        ^~~~~~~~~~~~
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:437:24: note:   no known conversion for argument 2 from ‘std::remove_reference<FnBoxWrapper&>::type {aka FnBoxWrapper}’ to ‘const char*’
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:454:24: note: candidate: static bool QMetaObject::invokeMethod(QObject*, const char*, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument)
cargo:warning=     static inline bool invokeMethod(QObject *obj, const char *member,
cargo:warning=                        ^~~~~~~~~~~~
cargo:warning=/usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs.h:454:24: note:   no known conversion for argument 2 from ‘std::remove_reference<FnBoxWrapper&>::type {aka FnBoxWrapper}’ to ‘const char*’
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "/home/verpfeilt/Git/qmetaobject-rs/qmetaobject" "-I" "/usr/include/x86_64-linux-gnu/qt5" "-Wall" "-Wextra" "-std=c++11" "-o" "/home/verpfeilt/Git/qmetaobject-rs/examples/todos/target/debug/build/qmetaobject-6f9106977441dc85/out/rust_cpp/cpp_closures.o" "-c" "/home/verpfeilt/Git/qmetaobject-rs/examples/todos/target/debug/build/qmetaobject-6f9106977441dc85/out/rust_cpp/cpp_closures.cpp" with args "c++" did not execute successfully (status code exit code: 1).

', /home/verpfeilt/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:479
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: cc::fail
             at /home/verpfeilt/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260
   8: cc::Build::compile
             at /home/verpfeilt/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:933
   9: cpp_build::Config::build
             at /home/verpfeilt/.cargo/registry/src/github.com-1ecc6299db9ec823/cpp_build-0.5.0/src/lib.rs:644
  10: build_script_build::main
             at ./build.rs:35
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start
```

</details>

**Comment by ogoffart** [comment]
I believe I have fixed this problem recently.  Travis is now running with Qt 5.9 and Qt 5.8
Please make sure you are using at least the 0.0.2 tag or the master branch.

**Comment by Pfeil** [comment]
Oh, yeah I forgot to pull on that machine, sorry -.-'.
